# Generated by Django 3.2.7 on 2021-11-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20211103_0545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='values',
            new_name='value',
        ),
    ]
